# -*- coding: utf-8 -*-
"""CodigoExamen.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KhGPyEwq-Qrrf7zbbvbzsWoZ5PCYOox7
"""

numero = int(input("Numero a validar: "))
contador = 0
lista = []
if numero < 0:
  print("Digite un numero positivo")
for inteligente in range(1,numero+1):
    if (numero % inteligente) == 0 :
        contador += 1
        lista.append(inteligente)
print(lista)
if len(lista) > 2:
  print("el numero",numero,"si es inteligente")
elif len(lista) <= 2:
    print("el numero",numero,"no es inteligente")

